### PR TITLE
112 parent selector circular deps

### LINKED ISSUE #112: Parent term selector is unable to handle ancestor cycles
When terms loaded by parent term selector contain an ancestor cycle (e.g., `A.parentTerms = [B], B.parentTerms=[C], C.parentTerms=[A]`), the component fails with an endless loop when processing the terms.

### PR DESCRIPTION
**Pull request by ledsoft**
Fixes #112

### CODE REVIEW

File: src/component/term/ParentTermSelector.tsx [hunk 1]
```diff
@@ -24,8 +24,24 @@ import { getLocalized } from "../../model/MultilingualString";
...
 
+export const PARENT_ATTRIBUTES = [
+  {
+    attribute: "parentTerms",
+    property: VocabularyUtils.BROADER,
+    labelKey: "term.metadata.parent",
+    selectorLabelKey: "term.metadata.broader",
+    selectorHintKey: "term.metadata.broader.hint",
+  },
+  ...TERM_BROADER_SUBPROPERTIES.slice(),
```
Comment (karelklima) [inline src/component/term/ParentTermSelector.tsx]: AFAIK the `.slice()` is unnecessary here. It creates a new array object as a shallow copy - the content is just references to elements in the original array. So as far as I can tell it doesn't really do anything here.

**Review by karelklima — DISMISSED** [review]

**Review by karelklima — APPROVED** [review]
